from __future__ import annotations

import shlex
import subprocess
from pathlib import Path
from typing import Any

from .commands import require_binary
from .names import slugify


def _quote(value: str) -> str:
    return shlex.quote(value)


def _launch_line(
    window: dict[str, Any],
    *,
    should_refocus: bool,
    workspace_name: str,
    workspace_kind: str,
    tab_title: str | None = None,
) -> str:
    parts = ["launch"]
    title = str(window.get("title") or "")
    cwd = window.get("cwd")
    parts.append(f"--env=KTR_WORKSPACE_NAME={_quote(workspace_name)}")
    parts.append(f"--env=KTR_WORKSPACE_KIND={_quote(workspace_kind)}")
    parts.append(f"--env=KTR_WORKSPACE_SLUG={_quote(slugify(workspace_name))}")
    if tab_title:
        parts.append(f"--tab-title={_quote(tab_title)}")
    if title:
        parts.append(f"--title={_quote(title)}")
    if cwd:
        parts.append(f"--cwd={_quote(str(cwd))}")
    if should_refocus:
        parts.append("--var=ktr_focus=1")
    return " ".join(parts)


def render_session(snapshot: dict[str, Any]) -> str:
    lines = [
        "# Generated by kitty-tabs-recover.",
        "# Scrollback text is saved beside snapshot.json; live processes are not resurrected.",
    ]

    os_title = snapshot.get("os_window", {}).get("title")
    workspace_name = str(snapshot.get("name") or os_title or "workspace")
    workspace_kind = str(snapshot.get("kind") or "named")
    if os_title:
        lines.append(f"os_window_title {_quote(str(os_title))}")

    for tab_index, tab in enumerate(snapshot.get("os_window", {}).get("tabs") or []):
        title = str(tab.get("title") or f"Tab {tab_index + 1}")
        if tab_index != 0:
            lines.append(f"new_tab {_quote(title)}")

        layout = tab.get("layout")
        if layout:
            lines.append(f"layout {_quote(str(layout))}")

        windows = tab.get("windows") or []
        if not windows:
            lines.append("launch")
            continue

        for window_index, window in enumerate(windows):
            lines.append(
                _launch_line(
                    window,
                    should_refocus=bool(window.get("is_active")),
                    workspace_name=workspace_name,
                    workspace_kind=workspace_kind,
                    tab_title=title if tab_index == 0 and window_index == 0 else None,
                )
            )
        if any(window.get("is_active") for window in windows):
            lines.append("focus_matching_window var:ktr_focus=1")

    active_tab_index = 0
    for tab in snapshot.get("os_window", {}).get("tabs") or []:
        if tab.get("is_active"):
            active_tab_index = int(tab.get("index") or 0)
            break
    if active_tab_index:
        lines.append(f"focus_tab {active_tab_index}")

    return "\n".join(lines) + "\n"


def write_session(snapshot_path: Path) -> Path:
    import json

    snapshot = json.loads(snapshot_path.read_text(encoding="utf-8"))
    session_path = snapshot_path.parent / "session.kitty"
    session_path.write_text(render_session(snapshot), encoding="utf-8")
    return session_path


def open_session(session_path: Path) -> None:
    require_binary("kitty")
    subprocess.Popen(["kitty", "--session", str(session_path)], start_new_session=True)
